-- GENERATED by scripts/generate-demo-schema.mjs from drizzle/meta/_journal.json.
-- Do not edit by hand. Regenerate with: npm run generate:demo-schema

-- 0000_init
CREATE TABLE IF NOT EXISTS "app_user" (
	"user_id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "app_user_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"email" text NOT NULL,
	"full_name" text,
	"language" text DEFAULT 'en' NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "company" (
	"company_fn" text PRIMARY KEY NOT NULL,
	"master_fn" text NOT NULL,
	"name" text NOT NULL,
	"country" text NOT NULL,
	"currency" text NOT NULL,
	"tax_regime" text NOT NULL,
	"locale" text DEFAULT 'en' NOT NULL,
	"fiscal_year_start" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "master" (
	"master_fn" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role" (
	"role_id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "role_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"name" text NOT NULL,
	"is_superadmin" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_company" (
	"user_id" bigint NOT NULL,
	"company_fn" text NOT NULL,
	"role_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_company_user_id_company_fn_pk" PRIMARY KEY("user_id","company_fn")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "currency" (
	"code" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"symbol" text,
	"decimals" integer DEFAULT 2 NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "fx_rate" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "fx_rate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"from_ccy" text NOT NULL,
	"to_ccy" text NOT NULL,
	"rate" numeric(18, 8) NOT NULL,
	"valid_from" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tax_rule" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "tax_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"tax_regime" text NOT NULL,
	"tax_code" text NOT NULL,
	"rate" numeric(6, 3) NOT NULL,
	"valid_from" date NOT NULL,
	"valid_to" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "product" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"sku" text NOT NULL,
	"name" text NOT NULL,
	"uom" text DEFAULT 'unit' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_level" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stock_level_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"product_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"qty" numeric(18, 4) DEFAULT '0' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "stock_movement" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stock_movement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"product_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"qty" numeric(18, 4) NOT NULL,
	"direction" text NOT NULL,
	"moved_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ref_type" text,
	"ref_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "warehouse" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "warehouse_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "customer" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "customer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invoice" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "invoice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"order_id" bigint NOT NULL,
	"customer_id" bigint NOT NULL,
	"status" text DEFAULT 'unpaid' NOT NULL,
	"invoice_date" date NOT NULL,
	"currency" text NOT NULL,
	"net_amount" numeric(18, 2) NOT NULL,
	"tax_amount" numeric(18, 2) NOT NULL,
	"total_amount" numeric(18, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sales_order" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sales_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"customer_id" bigint NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"order_date" date NOT NULL,
	"currency" text NOT NULL,
	"net_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"tax_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"total_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "sales_order_line" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "sales_order_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"order_id" bigint NOT NULL,
	"line_no" integer NOT NULL,
	"product_id" bigint NOT NULL,
	"qty" numeric(18, 4) NOT NULL,
	"unit_price" numeric(18, 4) NOT NULL,
	"net_amount" numeric(18, 2) NOT NULL,
	"tax_code" text NOT NULL,
	"tax_rate" numeric(6, 3) NOT NULL,
	"tax_amount" numeric(18, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "account" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "account_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "gl_entry" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "gl_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"posted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"journal_ref" text NOT NULL,
	"account_id" bigint NOT NULL,
	"debit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"credit" numeric(18, 2) DEFAULT '0' NOT NULL,
	"memo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "app_user" ADD CONSTRAINT "app_user_master_fn_master_master_fn_fk" FOREIGN KEY ("master_fn") REFERENCES "public"."master"("master_fn") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "company" ADD CONSTRAINT "company_master_fn_master_master_fn_fk" FOREIGN KEY ("master_fn") REFERENCES "public"."master"("master_fn") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "company" ADD CONSTRAINT "company_currency_currency_code_fk" FOREIGN KEY ("currency") REFERENCES "public"."currency"("code") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "role" ADD CONSTRAINT "role_master_fn_master_master_fn_fk" FOREIGN KEY ("master_fn") REFERENCES "public"."master"("master_fn") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_company" ADD CONSTRAINT "user_company_user_id_app_user_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_company" ADD CONSTRAINT "user_company_company_fn_company_company_fn_fk" FOREIGN KEY ("company_fn") REFERENCES "public"."company"("company_fn") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_company" ADD CONSTRAINT "user_company_role_id_role_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."role"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "fx_rate" ADD CONSTRAINT "fx_rate_from_ccy_currency_code_fk" FOREIGN KEY ("from_ccy") REFERENCES "public"."currency"("code") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "fx_rate" ADD CONSTRAINT "fx_rate_to_ccy_currency_code_fk" FOREIGN KEY ("to_ccy") REFERENCES "public"."currency"("code") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_level" ADD CONSTRAINT "stock_level_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_level" ADD CONSTRAINT "stock_level_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement" ADD CONSTRAINT "stock_movement_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_movement" ADD CONSTRAINT "stock_movement_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "invoice" ADD CONSTRAINT "invoice_order_id_sales_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."sales_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "invoice" ADD CONSTRAINT "invoice_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sales_order" ADD CONSTRAINT "sales_order_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sales_order_line" ADD CONSTRAINT "sales_order_line_order_id_sales_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."sales_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "sales_order_line" ADD CONSTRAINT "sales_order_line_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "gl_entry" ADD CONSTRAINT "gl_entry_account_id_account_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."account"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_user_master_email" ON "app_user" USING btree ("master_fn","email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_company_master" ON "company" USING btree ("master_fn");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_role_master_name" ON "role" USING btree ("master_fn","name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_user_company_company" ON "user_company" USING btree ("company_fn");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_fx_pair_from" ON "fx_rate" USING btree ("from_ccy","to_ccy","valid_from");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_tax_rule_lookup" ON "tax_rule" USING btree ("master_fn","company_fn","tax_code","valid_from");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_product_sku" ON "product" USING btree ("master_fn","company_fn","sku");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_product_name" ON "product" USING btree ("master_fn","company_fn","name");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_stock_level" ON "stock_level" USING btree ("master_fn","company_fn","product_id","warehouse_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_movement_tenant_moved" ON "stock_movement" USING btree ("master_fn","company_fn","moved_at","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_movement_product" ON "stock_movement" USING btree ("master_fn","company_fn","product_id","moved_at");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_warehouse_code" ON "warehouse" USING btree ("master_fn","company_fn","code");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_customer_code" ON "customer" USING btree ("master_fn","company_fn","code");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_invoice_docno" ON "invoice" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_invoice_order" ON "invoice" USING btree ("master_fn","company_fn","order_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_so_docno" ON "sales_order" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_so_tenant_date" ON "sales_order" USING btree ("master_fn","company_fn","order_date","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_sol_order" ON "sales_order_line" USING btree ("master_fn","company_fn","order_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_account_code" ON "account" USING btree ("master_fn","company_fn","code");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_gl_tenant_posted" ON "gl_entry" USING btree ("master_fn","company_fn","posted_at","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_gl_journal" ON "gl_entry" USING btree ("master_fn","company_fn","journal_ref");

-- 0001_quiet_blizzard
ALTER TABLE "app_user" ADD COLUMN "password_hash" text NOT NULL;

-- 0002_messy_slyde
CREATE TABLE IF NOT EXISTS "goods_receipt" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "goods_receipt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"order_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"received_date" date NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "purchase_order" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "purchase_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"supplier_id" bigint NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"order_date" date NOT NULL,
	"currency" text NOT NULL,
	"net_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"tax_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"total_amount" numeric(18, 2) DEFAULT '0' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "purchase_order_line" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "purchase_order_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"order_id" bigint NOT NULL,
	"line_no" integer NOT NULL,
	"product_id" bigint NOT NULL,
	"qty" numeric(18, 4) NOT NULL,
	"unit_cost" numeric(18, 4) NOT NULL,
	"net_amount" numeric(18, 2) NOT NULL,
	"tax_code" text NOT NULL,
	"tax_rate" numeric(6, 3) NOT NULL,
	"tax_amount" numeric(18, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "supplier" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "supplier_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "supplier_invoice" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "supplier_invoice_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"order_id" bigint NOT NULL,
	"supplier_id" bigint NOT NULL,
	"status" text DEFAULT 'unpaid' NOT NULL,
	"invoice_date" date NOT NULL,
	"currency" text NOT NULL,
	"net_amount" numeric(18, 2) NOT NULL,
	"tax_amount" numeric(18, 2) NOT NULL,
	"total_amount" numeric(18, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "goods_receipt" ADD CONSTRAINT "goods_receipt_order_id_purchase_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."purchase_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "goods_receipt" ADD CONSTRAINT "goods_receipt_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "purchase_order" ADD CONSTRAINT "purchase_order_supplier_id_supplier_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."supplier"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "purchase_order_line" ADD CONSTRAINT "purchase_order_line_order_id_purchase_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."purchase_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "purchase_order_line" ADD CONSTRAINT "purchase_order_line_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "supplier_invoice" ADD CONSTRAINT "supplier_invoice_order_id_purchase_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."purchase_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "supplier_invoice" ADD CONSTRAINT "supplier_invoice_supplier_id_supplier_id_fk" FOREIGN KEY ("supplier_id") REFERENCES "public"."supplier"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_gr_docno" ON "goods_receipt" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_gr_order" ON "goods_receipt" USING btree ("master_fn","company_fn","order_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_po_docno" ON "purchase_order" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_po_tenant_date" ON "purchase_order" USING btree ("master_fn","company_fn","order_date","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_pol_order" ON "purchase_order_line" USING btree ("master_fn","company_fn","order_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_supplier_code" ON "supplier" USING btree ("master_fn","company_fn","code");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_si_docno" ON "supplier_invoice" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_si_order" ON "supplier_invoice" USING btree ("master_fn","company_fn","order_id");

-- 0003_fuzzy_ronan
CREATE TABLE IF NOT EXISTS "activity" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"opportunity_id" bigint NOT NULL,
	"kind" text NOT NULL,
	"body" text NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "opportunity" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "opportunity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"customer_id" bigint NOT NULL,
	"title" text NOT NULL,
	"value" numeric(18, 2) NOT NULL,
	"currency" text NOT NULL,
	"stage" text DEFAULT 'lead' NOT NULL,
	"probability" numeric(5, 2) DEFAULT '0' NOT NULL,
	"close_date" date NOT NULL,
	"owner_user_id" bigint,
	"order_id" bigint,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "activity" ADD CONSTRAINT "activity_opportunity_id_opportunity_id_fk" FOREIGN KEY ("opportunity_id") REFERENCES "public"."opportunity"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opportunity" ADD CONSTRAINT "opportunity_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opportunity" ADD CONSTRAINT "opportunity_owner_user_id_app_user_user_id_fk" FOREIGN KEY ("owner_user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "opportunity" ADD CONSTRAINT "opportunity_order_id_sales_order_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."sales_order"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_activity_opportunity" ON "activity" USING btree ("master_fn","company_fn","opportunity_id","occurred_at");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_opp_docno" ON "opportunity" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opp_tenant_stage" ON "opportunity" USING btree ("master_fn","company_fn","stage","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_opp_customer" ON "opportunity" USING btree ("master_fn","company_fn","customer_id");

-- 0004_stormy_guardian
CREATE TABLE IF NOT EXISTS "api_idempotency" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "api_idempotency_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"actor_user_id" bigint NOT NULL,
	"idempotency_key" text NOT NULL,
	"operation" text NOT NULL,
	"request_hash" text NOT NULL,
	"response_status" integer,
	"response_body" jsonb,
	"completed_at" timestamp with time zone,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "app_session" (
	"token_hash" text PRIMARY KEY NOT NULL,
	"csrf_hash" text NOT NULL,
	"user_id" bigint NOT NULL,
	"master_fn" text NOT NULL,
	"active_company_fn" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"idle_expires_at" timestamp with time zone NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	"user_agent_hash" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "audit_log" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text,
	"actor_user_id" bigint,
	"request_id" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" text,
	"action" text NOT NULL,
	"before" jsonb,
	"after" jsonb,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "auth_rate_limit" (
	"identifier_hash" text PRIMARY KEY NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"window_started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"blocked_until" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "outbox_event" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "outbox_event_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"topic" text NOT NULL,
	"aggregate_type" text NOT NULL,
	"aggregate_id" text NOT NULL,
	"payload" jsonb NOT NULL,
	"available_at" timestamp with time zone DEFAULT now() NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"delivered_at" timestamp with time zone,
	"last_error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "password_reset_token" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "password_reset_token_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" bigint NOT NULL,
	"token_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "role_permission" (
	"master_fn" text NOT NULL,
	"role_id" bigint NOT NULL,
	"permission_key" text NOT NULL,
	"allowed" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "role_permission_role_id_permission_key_pk" PRIMARY KEY("role_id","permission_key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_invitation" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "user_invitation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"email" text NOT NULL,
	"role_id" bigint NOT NULL,
	"token_hash" text NOT NULL,
	"invited_by_user_id" bigint NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"accepted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "invoice" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "sales_order" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "purchase_order" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "supplier_invoice" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "opportunity" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "api_idempotency" ADD CONSTRAINT "api_idempotency_actor_user_id_app_user_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "app_session" ADD CONSTRAINT "app_session_user_id_app_user_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "app_session" ADD CONSTRAINT "app_session_active_company_fn_company_company_fn_fk" FOREIGN KEY ("active_company_fn") REFERENCES "public"."company"("company_fn") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_actor_user_id_app_user_user_id_fk" FOREIGN KEY ("actor_user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "password_reset_token" ADD CONSTRAINT "password_reset_token_user_id_app_user_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "role_permission" ADD CONSTRAINT "role_permission_role_id_role_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."role"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_invitation" ADD CONSTRAINT "user_invitation_role_id_role_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."role"("role_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user_invitation" ADD CONSTRAINT "user_invitation_invited_by_user_id_app_user_user_id_fk" FOREIGN KEY ("invited_by_user_id") REFERENCES "public"."app_user"("user_id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_idempotency_actor_key" ON "api_idempotency" USING btree ("master_fn","company_fn","actor_user_id","idempotency_key");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_idempotency_expiry" ON "api_idempotency" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_session_user" ON "app_session" USING btree ("master_fn","user_id","revoked_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_session_expiry" ON "app_session" USING btree ("expires_at","idle_expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_tenant_time" ON "audit_log" USING btree ("master_fn","company_fn","occurred_at","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_entity" ON "audit_log" USING btree ("master_fn","company_fn","entity","entity_id","occurred_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_audit_request" ON "audit_log" USING btree ("request_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_outbox_pending" ON "outbox_event" USING btree ("delivered_at","available_at","id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_outbox_tenant_aggregate" ON "outbox_event" USING btree ("master_fn","company_fn","aggregate_type","aggregate_id","id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_password_reset_token" ON "password_reset_token" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_password_reset_user" ON "password_reset_token" USING btree ("user_id","expires_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_role_permission_master" ON "role_permission" USING btree ("master_fn","permission_key","role_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "uq_invitation_token" ON "user_invitation" USING btree ("token_hash");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_invitation_tenant_email" ON "user_invitation" USING btree ("master_fn","company_fn","email");

-- 0005_magenta_terrax
CREATE TABLE IF NOT EXISTS "system_state" (
	"key" text PRIMARY KEY NOT NULL,
	"value" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "outbox_event" ADD COLUMN "locked_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "outbox_event" ADD COLUMN "locked_by" text;--> statement-breakpoint
ALTER TABLE "outbox_event" ADD COLUMN "last_attempt_at" timestamp with time zone;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "idx_outbox_lease" ON "outbox_event" USING btree ("delivered_at","locked_at","available_at","id");

-- 0006_uneven_korg
CREATE TABLE "inventory_adjustment" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "inventory_adjustment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"adjustment_date" date NOT NULL,
	"reason" text NOT NULL,
	"reference" text,
	"posted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inventory_adjustment_line" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "inventory_adjustment_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"adjustment_id" bigint NOT NULL,
	"line_no" integer NOT NULL,
	"product_id" bigint NOT NULL,
	"system_qty" numeric(18, 4) NOT NULL,
	"counted_qty" numeric(18, 4) NOT NULL,
	"variance_qty" numeric(18, 4) NOT NULL,
	"unit_cost" numeric(18, 4) NOT NULL,
	"value_impact" numeric(18, 2) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_transfer" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stock_transfer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"status" text DEFAULT 'draft' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"from_warehouse_id" bigint NOT NULL,
	"to_warehouse_id" bigint NOT NULL,
	"transfer_date" date NOT NULL,
	"reference" text,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stock_transfer_line" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stock_transfer_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"transfer_id" bigint NOT NULL,
	"line_no" integer NOT NULL,
	"product_id" bigint NOT NULL,
	"qty" numeric(18, 4) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "product" ADD COLUMN "standard_cost" numeric(18, 4) DEFAULT '0' NOT NULL;--> statement-breakpoint
ALTER TABLE "product" ADD COLUMN "tracking_type" text DEFAULT 'none' NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "inventory_adjustment" ADD CONSTRAINT "inventory_adjustment_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "inventory_adjustment_line" ADD CONSTRAINT "inventory_adjustment_line_adjustment_id_inventory_adjustment_id_fk" FOREIGN KEY ("adjustment_id") REFERENCES "public"."inventory_adjustment"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "inventory_adjustment_line" ADD CONSTRAINT "inventory_adjustment_line_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_transfer" ADD CONSTRAINT "stock_transfer_from_warehouse_id_warehouse_id_fk" FOREIGN KEY ("from_warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_transfer" ADD CONSTRAINT "stock_transfer_to_warehouse_id_warehouse_id_fk" FOREIGN KEY ("to_warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_transfer_line" ADD CONSTRAINT "stock_transfer_line_transfer_id_stock_transfer_id_fk" FOREIGN KEY ("transfer_id") REFERENCES "public"."stock_transfer"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "stock_transfer_line" ADD CONSTRAINT "stock_transfer_line_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null;
END $$;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inventory_adjustment_docno" ON "inventory_adjustment" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX "idx_inventory_adjustment_date" ON "inventory_adjustment" USING btree ("master_fn","company_fn","adjustment_date","id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inventory_adjustment_line" ON "inventory_adjustment_line" USING btree ("master_fn","company_fn","adjustment_id","line_no");--> statement-breakpoint
CREATE INDEX "idx_inventory_adjustment_line_product" ON "inventory_adjustment_line" USING btree ("master_fn","company_fn","product_id","adjustment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_stock_transfer_docno" ON "stock_transfer" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX "idx_stock_transfer_date" ON "stock_transfer" USING btree ("master_fn","company_fn","transfer_date","id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_stock_transfer_line" ON "stock_transfer_line" USING btree ("master_fn","company_fn","transfer_id","line_no");--> statement-breakpoint
CREATE INDEX "idx_stock_transfer_line_product" ON "stock_transfer_line" USING btree ("master_fn","company_fn","product_id","transfer_id");

-- 0007_wonderful_swordsman
CREATE TABLE "inventory_lot" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "inventory_lot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"product_id" bigint NOT NULL,
	"lot_no" text NOT NULL,
	"manufactured_date" date,
	"expiry_date" date,
	"quality_status" text DEFAULT 'released' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_inventory_lot_quality" CHECK ("inventory_lot"."quality_status" in ('released', 'hold', 'rejected'))
);
--> statement-breakpoint
CREATE TABLE "inventory_serial" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "inventory_serial_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"product_id" bigint NOT NULL,
	"serial_no" text NOT NULL,
	"lot_id" bigint,
	"status" text DEFAULT 'registered' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_inventory_serial_status" CHECK ("inventory_serial"."status" in ('registered', 'available', 'issued', 'scrapped'))
);
--> statement-breakpoint
CREATE TABLE "stock_location_balance" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stock_location_balance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"product_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"bin_id" bigint NOT NULL,
	"tracking_key" text DEFAULT 'none' NOT NULL,
	"lot_id" bigint,
	"serial_id" bigint,
	"qty" numeric(18, 4) DEFAULT '0' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_stock_location_nonnegative" CHECK ("stock_location_balance"."qty" >= 0),
	CONSTRAINT "ck_stock_location_tracking" CHECK (
    ("stock_location_balance"."tracking_key" = 'none' and "stock_location_balance"."lot_id" is null and "stock_location_balance"."serial_id" is null)
    or ("stock_location_balance"."tracking_key" like 'lot:%' and "stock_location_balance"."lot_id" is not null and "stock_location_balance"."serial_id" is null)
    or ("stock_location_balance"."tracking_key" like 'serial:%' and "stock_location_balance"."serial_id" is not null)
  ),
	CONSTRAINT "ck_stock_location_serial_qty" CHECK ("stock_location_balance"."serial_id" is null or "stock_location_balance"."qty" in (0, 1))
);
--> statement-breakpoint
CREATE TABLE "warehouse_bin" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "warehouse_bin_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"code" text NOT NULL,
	"name" text NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "stock_movement" ADD COLUMN "bin_id" bigint;--> statement-breakpoint
ALTER TABLE "stock_movement" ADD COLUMN "lot_id" bigint;--> statement-breakpoint
ALTER TABLE "stock_movement" ADD COLUMN "serial_id" bigint;--> statement-breakpoint
ALTER TABLE "stock_movement" ADD COLUMN "movement_group" text;--> statement-breakpoint
ALTER TABLE "inventory_lot" ADD CONSTRAINT "inventory_lot_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventory_serial" ADD CONSTRAINT "inventory_serial_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inventory_serial" ADD CONSTRAINT "inventory_serial_lot_id_inventory_lot_id_fk" FOREIGN KEY ("lot_id") REFERENCES "public"."inventory_lot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_location_balance" ADD CONSTRAINT "stock_location_balance_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_location_balance" ADD CONSTRAINT "stock_location_balance_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_location_balance" ADD CONSTRAINT "stock_location_balance_bin_id_warehouse_bin_id_fk" FOREIGN KEY ("bin_id") REFERENCES "public"."warehouse_bin"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_location_balance" ADD CONSTRAINT "stock_location_balance_lot_id_inventory_lot_id_fk" FOREIGN KEY ("lot_id") REFERENCES "public"."inventory_lot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_location_balance" ADD CONSTRAINT "stock_location_balance_serial_id_inventory_serial_id_fk" FOREIGN KEY ("serial_id") REFERENCES "public"."inventory_serial"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_bin" ADD CONSTRAINT "warehouse_bin_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inventory_lot_no" ON "inventory_lot" USING btree ("master_fn","company_fn","product_id","lot_no");--> statement-breakpoint
CREATE INDEX "idx_inventory_lot_expiry" ON "inventory_lot" USING btree ("master_fn","company_fn","product_id","expiry_date");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_inventory_serial_no" ON "inventory_serial" USING btree ("master_fn","company_fn","product_id","serial_no");--> statement-breakpoint
CREATE INDEX "idx_inventory_serial_status" ON "inventory_serial" USING btree ("master_fn","company_fn","product_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_stock_location_balance" ON "stock_location_balance" USING btree ("master_fn","company_fn","product_id","warehouse_id","bin_id","tracking_key");--> statement-breakpoint
CREATE INDEX "idx_stock_location_tracking" ON "stock_location_balance" USING btree ("master_fn","company_fn","product_id","tracking_key","warehouse_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_warehouse_bin_code" ON "warehouse_bin" USING btree ("master_fn","company_fn","warehouse_id","code");--> statement-breakpoint
CREATE INDEX "idx_warehouse_bin_active" ON "warehouse_bin" USING btree ("master_fn","company_fn","warehouse_id","is_active");--> statement-breakpoint
ALTER TABLE "stock_movement" ADD CONSTRAINT "stock_movement_bin_id_warehouse_bin_id_fk" FOREIGN KEY ("bin_id") REFERENCES "public"."warehouse_bin"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movement" ADD CONSTRAINT "stock_movement_lot_id_inventory_lot_id_fk" FOREIGN KEY ("lot_id") REFERENCES "public"."inventory_lot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_movement" ADD CONSTRAINT "stock_movement_serial_id_inventory_serial_id_fk" FOREIGN KEY ("serial_id") REFERENCES "public"."inventory_serial"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product" ADD CONSTRAINT "ck_product_tracking_type" CHECK ("product"."tracking_type" in ('none', 'lot', 'serial'));--> statement-breakpoint
ALTER TABLE "stock_movement" ADD CONSTRAINT "ck_stock_movement_direction" CHECK ("stock_movement"."direction" in ('in', 'out'));
--> statement-breakpoint
INSERT INTO "warehouse_bin" (
	"master_fn", "company_fn", "warehouse_id", "code", "name", "is_system", "is_active"
)
SELECT "master_fn", "company_fn", "id", 'DEFAULT', 'Default Bin', true, true
FROM "warehouse"
ON CONFLICT ("master_fn", "company_fn", "warehouse_id", "code") DO NOTHING;
--> statement-breakpoint
INSERT INTO "stock_location_balance" (
	"master_fn", "company_fn", "product_id", "warehouse_id", "bin_id",
	"tracking_key", "qty"
)
SELECT
	sl."master_fn", sl."company_fn", sl."product_id", sl."warehouse_id", wb."id",
	'none', sl."qty"
FROM "stock_level" sl
JOIN "warehouse_bin" wb
	ON wb."master_fn" = sl."master_fn"
	AND wb."company_fn" = sl."company_fn"
	AND wb."warehouse_id" = sl."warehouse_id"
	AND wb."code" = 'DEFAULT'
JOIN "product" p
	ON p."id" = sl."product_id"
	AND p."master_fn" = sl."master_fn"
	AND p."company_fn" = sl."company_fn"
WHERE p."tracking_type" = 'none'
ON CONFLICT (
	"master_fn", "company_fn", "product_id", "warehouse_id", "bin_id", "tracking_key"
) DO NOTHING;
--> statement-breakpoint
UPDATE "stock_movement" m
SET "bin_id" = wb."id"
FROM "warehouse_bin" wb
WHERE m."bin_id" IS NULL
	AND wb."master_fn" = m."master_fn"
	AND wb."company_fn" = m."company_fn"
	AND wb."warehouse_id" = m."warehouse_id"
	AND wb."code" = 'DEFAULT';

-- 0008_sweet_menace
CREATE TABLE "stock_reservation" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "stock_reservation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"pick_id" bigint NOT NULL,
	"pick_line_id" bigint NOT NULL,
	"product_id" bigint NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"bin_id" bigint NOT NULL,
	"qty" numeric(18, 4) NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_stock_reservation_qty" CHECK ("stock_reservation"."qty" > 0),
	CONSTRAINT "ck_stock_reservation_status" CHECK ("stock_reservation"."status" in ('active', 'consumed', 'released'))
);
--> statement-breakpoint
CREATE TABLE "warehouse_pick" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "warehouse_pick_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"doc_no" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"warehouse_id" bigint NOT NULL,
	"sales_order_id" bigint,
	"priority" text DEFAULT 'normal' NOT NULL,
	"assignee" text,
	"pick_date" date NOT NULL,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_warehouse_pick_status" CHECK ("warehouse_pick"."status" in ('open', 'in_progress', 'picked', 'cancelled'))
);
--> statement-breakpoint
CREATE TABLE "warehouse_pick_line" (
	"id" bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "warehouse_pick_line_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"master_fn" text NOT NULL,
	"company_fn" text NOT NULL,
	"pick_id" bigint NOT NULL,
	"line_no" integer NOT NULL,
	"product_id" bigint NOT NULL,
	"bin_id" bigint NOT NULL,
	"required_qty" numeric(18, 4) NOT NULL,
	"picked_qty" numeric(18, 4) DEFAULT '0' NOT NULL,
	"uom" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ck_warehouse_pick_line_qty" CHECK ("warehouse_pick_line"."required_qty" > 0 and "warehouse_pick_line"."picked_qty" >= 0 and "warehouse_pick_line"."picked_qty" <= "warehouse_pick_line"."required_qty")
);
--> statement-breakpoint
ALTER TABLE "stock_reservation" ADD CONSTRAINT "stock_reservation_pick_id_warehouse_pick_id_fk" FOREIGN KEY ("pick_id") REFERENCES "public"."warehouse_pick"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_reservation" ADD CONSTRAINT "stock_reservation_pick_line_id_warehouse_pick_line_id_fk" FOREIGN KEY ("pick_line_id") REFERENCES "public"."warehouse_pick_line"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_reservation" ADD CONSTRAINT "stock_reservation_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_reservation" ADD CONSTRAINT "stock_reservation_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stock_reservation" ADD CONSTRAINT "stock_reservation_bin_id_warehouse_bin_id_fk" FOREIGN KEY ("bin_id") REFERENCES "public"."warehouse_bin"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_pick" ADD CONSTRAINT "warehouse_pick_warehouse_id_warehouse_id_fk" FOREIGN KEY ("warehouse_id") REFERENCES "public"."warehouse"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_pick_line" ADD CONSTRAINT "warehouse_pick_line_pick_id_warehouse_pick_id_fk" FOREIGN KEY ("pick_id") REFERENCES "public"."warehouse_pick"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_pick_line" ADD CONSTRAINT "warehouse_pick_line_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "warehouse_pick_line" ADD CONSTRAINT "warehouse_pick_line_bin_id_warehouse_bin_id_fk" FOREIGN KEY ("bin_id") REFERENCES "public"."warehouse_bin"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "uq_stock_reservation_pick_line" ON "stock_reservation" USING btree ("master_fn","company_fn","pick_line_id");--> statement-breakpoint
CREATE INDEX "idx_stock_reservation_active" ON "stock_reservation" USING btree ("master_fn","company_fn","product_id","warehouse_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_warehouse_pick_docno" ON "warehouse_pick" USING btree ("master_fn","company_fn","doc_no");--> statement-breakpoint
CREATE INDEX "idx_warehouse_pick_status" ON "warehouse_pick" USING btree ("master_fn","company_fn","status","pick_date","id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_warehouse_pick_line" ON "warehouse_pick_line" USING btree ("master_fn","company_fn","pick_id","line_no");--> statement-breakpoint
CREATE INDEX "idx_warehouse_pick_line_product" ON "warehouse_pick_line" USING btree ("master_fn","company_fn","product_id","pick_id");
