/**
 * Tenant permission compatibility keys.
 *
 * These identifiers are kept in a dependency-free module so the permission
 * registry can describe and resolve them without importing the authorization
 * query service. They remain valid during the TASK-171 migration; new
 * protected operations should use permissionRegistry.canonicalPermissionForResource.
 */
export const PERMISSIONS = {
  dashboardRead: 'dashboard.read',
  inventoryRead: 'inventory.read',
  inventoryWrite: 'inventory.write',
  inventoryAdjust: 'inventory.adjust',
  inventoryTransfer: 'inventory.transfer',
  inventoryTrack: 'inventory.track',
  warehouseRead: 'warehouse.read',
  salesRead: 'sales.read',
  salesWrite: 'sales.write',
  salesApprove: 'sales.approve',
  salesCommissionApprove: 'sales.commission.approve',
  financeRead: 'finance.read',
  financeWrite: 'finance.write',
  financeBudgetManage: 'finance.budget.manage',
  financeBudgetApprove: 'finance.budget.approve',
  financeReportExport: 'finance.report.export',
  purchasingRead: 'purchasing.read',
  purchasingWrite: 'purchasing.write',
  purchasingApprove: 'purchasing.approve',
  crmRead: 'crm.read',
  crmWrite: 'crm.write',
  manufacturingRead: 'manufacturing.read',
  manufacturingWrite: 'manufacturing.write',
  qualityRead: 'quality.read',
  qualityWrite: 'quality.write',
  assetRead: 'asset.read',
  assetWrite: 'asset.write',
  hrRead: 'hr.read',
  hrWrite: 'hr.write',
  employeeSelfRead: 'employee.self.read',
  employeeLeaveWrite: 'employee.leave.write',
  employeeReceiptsWrite: 'employee.receipts.write',
  employeeClaimsWrite: 'employee.claims.write',
  employeePayoutManage: 'employee.payout.manage',
  documentsGovernanceManage: 'documents.governance.manage',
  documentsRecordsManage: 'documents.records.manage',
  documentsFinanceReview: 'documents.finance.review',
  expensesPolicyManage: 'expenses.policy.manage',
  expensesFinanceVerify: 'expenses.finance.verify',
  expensesManagerApprove: 'expenses.approve.manager',
  expensesFinanceApprove: 'expenses.approve.finance',
  expensesBudgetApprove: 'expenses.approve.budget',
  expensesDuplicateOverride: 'expenses.duplicate.override',
  expensesCardManage: 'expenses.card.manage',
  expensesAllowanceManage: 'expenses.allowance.manage',
  expensesAdvanceManage: 'expenses.advance.manage',
  expensesPayoutVerify: 'expenses.payout.verify',
  expensesPayoutReveal: 'expenses.payout.reveal',
  expensesPaymentBatchPrepare: 'expenses.payment.prepare',
  expensesPaymentBatchRelease: 'expenses.payment.release',
  expensesPaymentTemplateManage: 'expenses.payment.template.manage',
  expensesPaymentExport: 'expenses.payment.export',
  expensesPaymentResultImport: 'expenses.payment.result.import',
  expensesPaymentArtifactDownload: 'expenses.payment.artifact.download',
  expensesTaxEvidenceGenerate: 'expenses.tax_evidence.generate',
  expensesTaxEvidenceAccess: 'expenses.tax_evidence.access',
  expensesTaxEvidenceGovernance: 'expenses.tax_evidence.governance',
  employeeTeamRead: 'employee.team.read',
  projectRead: 'project.read',
  projectWrite: 'project.write',
  serviceRead: 'service.read',
  serviceWrite: 'service.write',
  reportingRead: 'reporting.read',
  integrationRead: 'integration.read',
  integrationImport: 'integration.import',
  integrationManage: 'integration.manage',
  notificationsRead: 'notifications.read',
  notificationsManage: 'notifications.manage',
  payrollRead: 'payroll.read',
  payrollWrite: 'payroll.write',
  companySwitch: 'session.switch_company',
  auditRead: 'admin.audit.read',
  usersInvite: 'admin.users.invite',
  usersRead: 'admin.users.read',
  usersManage: 'admin.users.manage',
  rolesRead: 'admin.roles.read',
  rolesWrite: 'admin.roles.write',
  modulesManage: 'admin.modules.manage',
  masterControlRead: 'admin.master.read',
  settingsRead: 'settings.read',
  settingsManage: 'settings.manage',
} as const;

export type TenantPermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];
